set -e
true
true
/home/neel/SPAdes-4.3.0-Linux/bin/spades-core /home/neel/bioinfo_project/massembly1/K21/configs/config.info /home/neel/bioinfo_project/massembly1/K21/configs/isolate_mode.info
/home/neel/SPAdes-4.3.0-Linux/bin/spades-core /home/neel/bioinfo_project/massembly1/K33/configs/config.info /home/neel/bioinfo_project/massembly1/K33/configs/isolate_mode.info
/usr/bin/python3 /home/neel/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/copy_files.py /home/neel/bioinfo_project/massembly1/K33/before_rr.fasta /home/neel/bioinfo_project/massembly1/before_rr.fasta /home/neel/bioinfo_project/massembly1/K33/assembly_graph_after_simplification.gfa /home/neel/bioinfo_project/massembly1/assembly_graph_after_simplification.gfa /home/neel/bioinfo_project/massembly1/K33/final_contigs.fasta /home/neel/bioinfo_project/massembly1/contigs.fasta /home/neel/bioinfo_project/massembly1/K33/first_pe_contigs.fasta /home/neel/bioinfo_project/massembly1/first_pe_contigs.fasta /home/neel/bioinfo_project/massembly1/K33/strain_graph.gfa /home/neel/bioinfo_project/massembly1/strain_graph.gfa /home/neel/bioinfo_project/massembly1/K33/scaffolds.fasta /home/neel/bioinfo_project/massembly1/scaffolds.fasta /home/neel/bioinfo_project/massembly1/K33/scaffolds.paths /home/neel/bioinfo_project/massembly1/scaffolds.paths /home/neel/bioinfo_project/massembly1/K33/assembly_graph_with_scaffolds.gfa /home/neel/bioinfo_project/massembly1/assembly_graph_with_scaffolds.gfa /home/neel/bioinfo_project/massembly1/K33/assembly_graph.fastg /home/neel/bioinfo_project/massembly1/assembly_graph.fastg /home/neel/bioinfo_project/massembly1/K33/final_contigs.paths /home/neel/bioinfo_project/massembly1/contigs.paths
true
/usr/bin/python3 /home/neel/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/breaking_scaffolds_script.py --result_scaffolds_filename /home/neel/bioinfo_project/massembly1/scaffolds.fasta --misc_dir /home/neel/bioinfo_project/massembly1/misc --threshold_for_breaking_scaffolds 3
true
