set -e
true
true
/home/neel/SPAdes-4.3.0-Linux/bin/spades-core /home/neel/bioinfo_project/nassembly2/K21/configs/config.info /home/neel/bioinfo_project/nassembly2/K21/configs/isolate_mode.info
/home/neel/SPAdes-4.3.0-Linux/bin/spades-core /home/neel/bioinfo_project/nassembly2/K33/configs/config.info /home/neel/bioinfo_project/nassembly2/K33/configs/isolate_mode.info
/home/neel/bioinfo_project/.venv/bin/python3 /home/neel/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/copy_files.py /home/neel/bioinfo_project/nassembly2/K33/before_rr.fasta /home/neel/bioinfo_project/nassembly2/before_rr.fasta /home/neel/bioinfo_project/nassembly2/K33/assembly_graph_after_simplification.gfa /home/neel/bioinfo_project/nassembly2/assembly_graph_after_simplification.gfa /home/neel/bioinfo_project/nassembly2/K33/final_contigs.fasta /home/neel/bioinfo_project/nassembly2/contigs.fasta /home/neel/bioinfo_project/nassembly2/K33/first_pe_contigs.fasta /home/neel/bioinfo_project/nassembly2/first_pe_contigs.fasta /home/neel/bioinfo_project/nassembly2/K33/strain_graph.gfa /home/neel/bioinfo_project/nassembly2/strain_graph.gfa /home/neel/bioinfo_project/nassembly2/K33/scaffolds.fasta /home/neel/bioinfo_project/nassembly2/scaffolds.fasta /home/neel/bioinfo_project/nassembly2/K33/scaffolds.paths /home/neel/bioinfo_project/nassembly2/scaffolds.paths /home/neel/bioinfo_project/nassembly2/K33/assembly_graph_with_scaffolds.gfa /home/neel/bioinfo_project/nassembly2/assembly_graph_with_scaffolds.gfa /home/neel/bioinfo_project/nassembly2/K33/assembly_graph.fastg /home/neel/bioinfo_project/nassembly2/assembly_graph.fastg /home/neel/bioinfo_project/nassembly2/K33/final_contigs.paths /home/neel/bioinfo_project/nassembly2/contigs.paths
true
/home/neel/bioinfo_project/.venv/bin/python3 /home/neel/SPAdes-4.3.0-Linux/share/spades/spades_pipeline/supplemetary/breaking_scaffolds_script.py --result_scaffolds_filename /home/neel/bioinfo_project/nassembly2/scaffolds.fasta --misc_dir /home/neel/bioinfo_project/nassembly2/misc --threshold_for_breaking_scaffolds 3
true
